:schedule:
  update_open_close_stock_price_update_worker_morning:
    cron: '30 09 * * * America/New_York'
    class: UpdateOpenCloseStockPriceWorker

  update_open_close_stock_price_update_worker_evening:
    cron: '30 16 * * * America/New_York'
    class: UpdateOpenCloseStockPriceWorker

  stock_price_update_worker:
    class: StockPriceUpdateWorker
    every: '30s'

  update_market_price_worker:
    class: UpdateMarketPriceWorker
    every: '60s'

  update_dividends_worker:
    class: UpdateDividendsWorker
    cron: '0 * * * * America/New_York'
